### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by Jamalam360** [Jamalam360/odot-backend#1]
- [ ] Implement task Endpoints
- [ ] Implement label Endpoints
- [ ] Implement sign-up confirmation emails
- [ ] Implement confirmation emails
- [ ] Token generation should be standardised (API authorisation and confirmation email tokens)
